### ISSUE TITLE
Same keys get overridden

### ISSUE THREAD

**Issue by ndabAP** [javisperez/vuetranslate#4]
When defining locales like this:

```
locales: {
  en: {
    'key': 'value'
  }
}
```
Another component with the same key value pair in the same environment overrides the component.

**Comment by javisperez** [comment]
Hey, sorry the late response, I've been really busy lately, my bad!

Thank you for opening an issue and yeah, that's kind of expected, all keys are global, the `locales` option are merged in the end.

I like your idea of having it in a local scope, might add that change at some point, but as I said I'm not sure when :-\ sorry about that.

If you by chance get to implement it, a PR is very welcome and appreciated :)

When I get to make this change I'll comment on this PR, meanwhile, I'll close it as that's the expected behavior right now.

Thanks again.
